import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const stocks=[
 {symbol:'RELIANCE',name:'Reliance Industries',price:'1,464.20',change:'+1.42%',positive:true,sector:'Energy & Telecom',score:78,tag:'Strong setup'},
 {symbol:'TCS',name:'Tata Consultancy Services',price:'3,188.60',change:'+0.84%',positive:true,sector:'Information Technology',score:74,tag:'Constructive'},
 {symbol:'HDFCBANK',name:'HDFC Bank',price:'1,942.35',change:'-0.38%',positive:false,sector:'Financial Services',score:69,tag:'Watchlist'},
 {symbol:'BHARTIARTL',name:'Bharti Airtel',price:'1,724.80',change:'+2.16%',positive:true,sector:'Telecommunication',score:82,tag:'Strong setup'},
 {symbol:'INFY',name:'Infosys',price:'1,536.10',change:'+0.22%',positive:true,sector:'Information Technology',score:71,tag:'Constructive'}
];
const movers=[['BHARTIARTL','Bharti Airtel','+2.16%'],['RELIANCE','Reliance Industries','+1.42%'],['TCS','Tata Consultancy Services','+0.84%'],['HDFCBANK','HDFC Bank','-0.38%']];
function Icon({children}){return <span className="icon">{children}</span>}
function App(){
 const [active,setActive]=useState('Overview'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState(null); const [started,setStarted]=useState(false);
 const filtered=useMemo(()=>stocks.filter(s=>(s.name+s.symbol).toLowerCase().includes(query.toLowerCase())),[query]);
 return <div className="app">
  <header><div className="brand"><div className="logo">⌁</div><div><strong>MarketLens</strong><small>Clarity for every market move</small></div></div><nav>{['Overview','Screener','Watchlist','Learn'].map(x=><button className={active===x?'nav active':'nav'} onClick={()=>setActive(x)} key={x}>{x}</button>)}</nav><button className="search-btn" onClick={()=>document.querySelector('.search').focus()}>⌕ <span>Search</span></button><button className="menu">☰</button></header>
  {!started?<main className="landing"><div className="eyebrow"><span className="pulse"></span> INDIAN MARKETS · RESEARCH, REIMAGINED</div><h1>See the market<br/><em>with clarity.</em></h1><p className="hero-copy">MarketLens brings price action, business fundamentals and market context together — then explains what matters in plain language.</p><div className="hero-actions"><button className="primary" onClick={()=>setStarted(true)}>Start analyzing <span>→</span></button><button className="ghost" onClick={()=>document.getElementById('how').scrollIntoView()}>How it works <span>↓</span></button></div><div className="hero-note"><span>◉</span> Data-led insights, not promises. Markets carry risk.</div><div className="orbit"><div className="orbit-ring"></div><div className="orb-card card-a"><small>NIFTY 50</small><b>25,215.90</b><span className="up">↗ 0.68%</span></div><div className="orb-card card-b"><small>MARKET PULSE</small><b>Positive</b><span className="muted">62% advancing</span></div><div className="orb-center"><span>ML</span></div></div><section id="how" className="features"><div><span className="feature-num">01</span><h3>Understand</h3><p>Financial data translated into clear, useful context.</p></div><div><span className="feature-num">02</span><h3>Compare</h3><p>Find strength across price, quality and valuation.</p></div><div><span className="feature-num">03</span><h3>Decide better</h3><p>See scenarios, risks and what to monitor next.</p></div></section></main>:
  <main className="dashboard"><div className="dash-top"><div><div className="eyebrow">MARKET OVERVIEW <span className="live-dot"></span> OPEN</div><h1>Good afternoon, investor.</h1><p>Here is what is moving across the Indian market today.</p></div><div className="date">22 AUG 2026<br/><small>Saturday · IST</small></div></div><div className="search-wrap"><span>⌕</span><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a stock, symbol or sector..."/><kbd>⌘ K</kbd></div><section className="index-grid">{[['NIFTY 50','25,215.90','+0.68%'],['SENSEX','82,365.77','+0.52%'],['NIFTY BANK','56,140.20','-0.14%'],['INDIA VIX','13.42','-2.81%']].map((x,i)=><div className="index-card" key={x[0]}><div><small>{x[0]}</small><strong>{x[1]}</strong><span className={x[2][0]=='-'?'down':'up'}>{x[2]}</span></div><div className={'spark s'+i}>╱╲╱╱╲╱╲</div></div>)}</section><div className="content-grid"><section className="panel"><div className="panel-head"><div><h2>Stocks to watch</h2><p>Signals based on multiple market factors</p></div><button className="text-btn">View screener →</button></div><div className="stock-list">{filtered.map(s=><button className="stock-row" onClick={()=>setSelected(s)} key={s.symbol}><div className="stock-icon">{s.symbol.slice(0,2)}</div><div className="stock-name"><b>{s.name}</b><small>{s.symbol} · {s.sector}</small></div><span className="tag">{s.tag}</span><div className="stock-price"><b>₹{s.price}</b><span className={s.positive?'up':'down'}>{s.change}</span></div><span className="arrow">→</span></button>)}</div>{!filtered.length&&<p className="empty">No stocks found. Try another symbol.</p>}</section><aside className="panel movers"><div className="panel-head"><div><h2>Market pulse</h2><p>Most active from your universe</p></div></div>{movers.map(m=><div className="mover" key={m[0]}><div className="mini-icon">{m[0].slice(0,2)}</div><div><b>{m[1]}</b><small>{m[0]}</small></div><span className={m[2][0]=='-'?'down':'up'}>{m[2]}</span></div>)}<div className="tip"><b>Lens tip</b><p>Momentum is positive today, but always check valuation and risk before acting.</p></div></aside></div><div className="disclaimer">MarketLens is a research and education tool. Information may be delayed and is not investment advice. Market investments are subject to risk.</div></main>}
  <footer><span>MarketLens</span><span>Made by Rishu Jaswar</span><span>Research clearly · Invest responsibly</span></footer>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">STOCK LENS · {selected.symbol}</div><h2>{selected.name}</h2><div className="modal-price">₹{selected.price} <span className="up">{selected.change}</span></div><div className="report"><b>Research view · {selected.tag}</b><p>This stock is showing a positive setup based on current price momentum and market context. This is a starting point for research, not a guaranteed prediction.</p><div className="metrics"><span><small>Overall score</small><b>{selected.score}/100</b></span><span><small>Time horizon</small><b>Medium term</b></span><span><small>Risk level</small><b>Moderate</b></span></div></div><button className="primary full">Open full analysis →</button></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
