import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const symbols=['RELIANCE','TCS','INFY','HDFCBANK','BHARTIARTL'];
const money=v=>v==null?'—':`₹${Number(v).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const pct=v=>v==null?'—':`${Number(v)>0?'+':''}${Number(v).toFixed(2)}%`;
function App(){
 const [started,setStarted]=useState(false),[query,setQuery]=useState(''),[stocks,setStocks]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const rows=await Promise.all(symbols.map(async s=>{const r=await fetch(`/api/market?symbol=${s}`);const d=await r.json();if(!r.ok) throw Error(d.error||'Market data unavailable');return d}));setStocks(rows)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(started)load()},[started]);
 const filtered=stocks.filter(s=>(s.symbol||'').toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><header><div className="brand"><div className="logo">⌁</div><div><strong>MarketLens</strong><small>Clarity for every market move</small></div></div><nav><button className="nav active">Overview</button><button className="nav">Screener</button><button className="nav">Watchlist</button></nav><button className="menu">☰</button></header>
 {!started?<main className="landing"><div className="eyebrow"><span className="pulse"/> INDIAN MARKETS · LIVE RESEARCH</div><h1>See the market<br/><em>with clarity.</em></h1><p className="hero-copy">MarketLens brings verified market data, business fundamentals and market context together — then explains what matters in plain language.</p><div className="hero-actions"><button className="primary" onClick={()=>setStarted(true)}>Start analyzing <span>→</span></button><button className="ghost" onClick={()=>document.getElementById('how').scrollIntoView()}>How it works <span>↓</span></button></div><div className="hero-note">◉ Live data only · no invented prices · market information may be delayed</div><div className="orbit"><div className="orbit-ring"/><div className="orb-center"><span>ML</span></div><div className="orb-card card-a"><small>DATA FIRST</small><b>Verified feeds</b><span className="muted">Provider timestamped</span></div><div className="orb-card card-b"><small>RESEARCH</small><b>Explainable</b><span className="muted">Risk before reward</span></div></div><section id="how" className="features"><div><span className="feature-num">01</span><h3>Connect</h3><p>Pull current information from your configured data provider.</p></div><div><span className="feature-num">02</span><h3>Analyze</h3><p>Calculate transparent indicators from verified market data.</p></div><div><span className="feature-num">03</span><h3>Understand</h3><p>Read scenarios, risks and context in simple language.</p></div></section></main>:
 <main className="dashboard"><div className="dash-top"><div><div className="eyebrow">MARKET OVERVIEW <span className="live-dot"/> API CONNECTED</div><h1>Market dashboard.</h1><p>Live information from your configured market-data provider.</p></div><button className="refresh" onClick={load}>↻ Refresh</button></div><div className="search-wrap"><span>⌕</span><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search loaded symbols..."/></div>{error&&<div className="api-error"><b>Live data unavailable</b><span>{error}</span><small>Configure FMP_API_KEY in Vercel Environment Variables, then redeploy.</small></div>}{loading&&<div className="loading">Fetching verified market data…</div>} {!loading&&!error&&stocks.length>0&&<><div className="data-banner">● LIVE RESPONSE · Last provider update: {new Date(stocks[0].updatedAt).toLocaleString()}</div><div className="content-grid"><section className="panel"><div className="panel-head"><div><h2>Loaded stocks</h2><p>Quotes returned by the configured API</p></div></div><div className="stock-list">{filtered.map(s=><button className="stock-row" onClick={()=>setSelected(s)} key={s.symbol}><div className="stock-icon">{s.symbol.slice(0,2)}</div><div className="stock-name"><b>{s.symbol}</b><small>Provider: {s.source}</small></div><div className="stock-price"><b>{money(s.price)}</b><span className={Number(s.changePercent)>=0?'up':'down'}>{pct(s.changePercent)}</span></div><span className="arrow">→</span></button>)}</div></section><aside className="panel"><div className="panel-head"><div><h2>Data quality</h2><p>Always inspect freshness and coverage</p></div></div><div className="quality"><span className="quality-dot"/><b>Verified API response</b></div><div className="quality-line"><span>Source</span><b>{stocks[0].source}</b></div><div className="quality-line"><span>Quotes loaded</span><b>{stocks.length}</b></div><div className="quality-line"><span>Fallback status</span><b>Not used</b></div><div className="tip"><b>Research note</b><p>A positive price move is not a recommendation. Check fundamentals, valuation, liquidity and risk before acting.</p></div></aside></div></>}{!loading&&!error&&!stocks.length&&<div className="empty">No provider data returned.</div>}<div className="disclaimer">MarketLens is a research and education tool. It does not guarantee returns or provide personalized investment advice. Market investments are subject to risk.</div></main>}
 <footer><span>MarketLens</span><span>Made by Rishu Jaswar</span><span>Research clearly · Invest responsibly</span></footer>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">LIVE QUOTE · {selected.symbol}</div><h2>{selected.symbol}</h2><div className="modal-price">{money(selected.price)} <span className={Number(selected.changePercent)>=0?'up':'down'}>{pct(selected.changePercent)}</span></div><div className="report"><b>Verified provider data</b><div className="metrics"><span><small>Open</small><b>{money(selected.open)}</b></span><span><small>Day high</small><b>{money(selected.dayHigh)}</b></span><span><small>Volume</small><b>{selected.volume?.toLocaleString('en-IN')||'—'}</b></span></div><p>AI research reports will be generated only from verified metrics after the Groq key and report workflow are configured.</p></div></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
