function numberOrNull(value) {
  if (
    value === null ||
    value === undefined ||
    value === ""
  ) {
    return null;
  }

  const number = Number(value);

  return Number.isFinite(number)
    ? number
    : null;
}

function cleanText(value, maxLength = 80) {
  return String(value || "")
    .trim()
    .slice(0, maxLength);
}

export default async function handler(
  req,
  res
) {
  if (req.method !== "POST") {
    return res.status(405).json({
      error: "POST required."
    });
  }

  const {
    stock,
    metrics
  } = req.body || {};

  if (
    !stock ||
    !metrics ||
    typeof metrics !== "object"
  ) {
    return res.status(400).json({
      error:
        "Verified stock data and metrics are required."
    });
  }

  const apiKey =
    process.env.GROQ_API_KEY;

  if (!apiKey) {
    return res.status(503).json({
      error:
        "Groq AI service is not configured."
    });
  }

  const verifiedMetrics = {
    symbol: cleanText(
      stock.symbol,
      40
    ),

    name: cleanText(
      stock.name ||
      stock.symbol,
      120
    ),

    exchange: cleanText(
      stock.exchange,
      60
    ),

    source: cleanText(
      metrics.source,
      100
    ),

    updatedAt: cleanText(
      metrics.updatedAt,
      80
    ),

    price: numberOrNull(
      metrics.price
    ),

    change: numberOrNull(
      metrics.change
    ),

    changePercent: numberOrNull(
      metrics.changePercent
    ),

    open: numberOrNull(
      metrics.open
    ),

    previousClose: numberOrNull(
      metrics.previousClose
    ),

    dayHigh: numberOrNull(
      metrics.dayHigh
    ),

    dayLow: numberOrNull(
      metrics.dayLow
    ),

    volume: numberOrNull(
      metrics.volume
    )
  };

  if (
    !verifiedMetrics.symbol ||
    verifiedMetrics.price === null
  ) {
    return res.status(400).json({
      error:
        "Groq analysis requires a verified market quote."
    });
  }

  const prompt = `
You are the analysis layer of MarketLens.

Analyze ONLY the verified market metrics supplied below.

VERIFIED DATA:
${JSON.stringify(
  verifiedMetrics,
  null,
  2
)}

STRICT DATA RULES:

1. Treat the VERIFIED DATA block as the only source for current numerical market facts.
2. Never change, replace, or contradict any verified number.
3. Do not invent:
   - another current price
   - market cap
   - P/E ratio
   - revenue
   - profit
   - news
   - earnings results
   - analyst targets
   - dividends
   - technical indicators not calculable from the supplied metrics
4. Do not claim to have browsed the web.
5. If information is missing, clearly say it cannot be determined from the supplied verified data.
6. Do not give BUY, SELL, HOLD, or guaranteed-return advice.
7. Explain what the verified price movement and trading range may indicate in cautious educational language.

Return ONLY valid JSON with exactly these keys:

headline,
summary,
marketRead,
strengths,
risks,
whatToMonitor,
limitations,
dataIntegrity

Required meaning:

headline:
Short neutral headline.

summary:
2 to 4 sentences using the verified metrics accurately.

marketRead:
Explain the current price movement, day range, and available volume data.
If volume or another metric is missing, explicitly say it is unavailable.

strengths:
Array of 3 cautious observations based only on supplied metrics.

risks:
Array of 3 to 5 risk or uncertainty points.
Do not invent company-specific facts.

whatToMonitor:
Array of 4 things the user should verify with real current data before making any decision.

limitations:
State which important analysis cannot be completed from this quote alone.

dataIntegrity:
Must state that the analysis used provider-backed metrics supplied by MarketLens and that no new market price was generated by AI.
`;

  try {
    const response = await fetch(
      "https://api.groq.com/openai/v1/chat/completions",
      {
        method: "POST",

        headers: {
          "Content-Type":
            "application/json",

          Authorization:
            `Bearer ${apiKey}`
        },

        body: JSON.stringify({
          model:
            process.env.GROQ_MODEL ||
            "llama-3.3-70b-versatile",

          temperature: 0.1,

          response_format: {
            type: "json_object"
          },

          messages: [
            {
              role: "system",

              content:
                "You are a precise financial-data interpretation assistant. You never fabricate current market information and you never provide personalized investment advice."
            },

            {
              role: "user",

              content: prompt
            }
          ]
        })
      }
    );

    const data =
      await response.json();

    if (!response.ok) {
      return res.status(
        response.status
      ).json({
        error:
          "Groq analysis request failed.",

        details:
          data?.error?.message ||
          data?.error ||
          "Unknown AI provider error."
      });
    }

    const content =
      data?.choices?.[0]
        ?.message?.content;

    if (!content) {
      return res.status(502).json({
        error:
          "Groq returned an empty analysis."
      });
    }

    let report;

    try {
      report =
        JSON.parse(content);
    } catch {
      return res.status(502).json({
        error:
          "Groq returned invalid analysis data."
      });
    }

    return res.status(200).json({
      report,

      analysisSource:
        "Groq interpretation of verified MarketLens metrics",

      verifiedMetrics
    });
  } catch (error) {
    return res.status(502).json({
      error:
        error instanceof Error
          ? error.message
          : "Unable to generate AI analysis."
    });
  }
}